### ISSUE TITLE
about the name

### ISSUE THREAD

**Issue by targos** [mljs/curve-fitting#1]
this project is named `curve-fitting` which is a pretty general name. However, it exports directly a specific algorithm and the readme is clear about the fact that it is the "Levenberg Marquardt" curve fitting.
I think one of the two following things should be done for consistency:
- rename the project to include levenberg-marquardt. Probably `ml-levenberg-marquardt` on npm, with `curve` and `fitting` in the keywords. On github we can be more explicit: `levenberg-marquardt-curve-fitting`.
- change the structure to allow to add more algorithms in the future

I personally prefer the rename approach.

**Comment by andcastillo** [comment]
I prefer the second one. Levenberg Marquardt is a general optimisation method. So we would have to rename it to Levenberg Marquardt curve-fitting, which is a little long.

**Comment by targos** [comment]
the name in github does not matter, it can be changed at any time, and the more precise it is, the easiest it is to find.
On the other hand, the npm name cannot really change and it should be small and recognisable. That said, what do you (and other @mljs/collaborators) think about `ml-levenberg-marquardt` ?

**Comment by 0x33467** [comment]
I think that `ml-curve-fitting` is ok, in the description of the npm package you can put `levenberg-marquardt` if you want to search by that name, no?

**Comment by maasencioh** [comment]
I prefer to change the structure to allow to add more algorithms in the future, as you said, it's a general problem and could be used in the future

**Comment by targos** [comment]
OK then, let's do that.
